### ISSUE TITLE
აპლიკაციის სქრინები

### ISSUE THREAD

**Issue by jibla** [GiorgiGagnidze/FreeUni-Swift-2015-Final-Project---Prava#2]
Wiki-ში გვერდის შექმნა სადაც ჩამოწერილი იქნება რა სქრინები აქვს აპლიკაციას და მიახლოებით მოკაპები აიტვირთება ხოლმე.

ეს თასქი დასრულებულია, როცა:
- ვიკიში შექმნილია სპეციალური გვერდი ამისთვის
- ჩამოწერილია ყველა სქრინი (დაახლოებით ცხადია, რაც ახლა ვიცით და შემდეგ დაემატება) რაც აპლიკაციაში იქნება

გვერდს რო გააკეთებთ კომენტარში დალინკეთ.

**Comment by jibla** [comment]
@GiorgiGagnidze @nikoloz14

**Comment by nikoloz14** [comment]
https://github.com/GiorgiGagnidze/FreeUni-Swift-2015-Final-Project---Prava/wiki
