### ISSUE TITLE
ბრენჩის სახელის შეცვლა

### ISSUE THREAD

**Issue by jibla** [GiorgiGagnidze/FreeUni-Swift-2015-Final-Project---Prava#5]
ბრენჩს Developer სახელი გადაარქვით develop.

**Comment by jibla** [comment]
და მასტერზე 22 კომიტი რატო გაქვთ? როგორც ჩანს ვიღაც ყოველ ჯერზე მასტერზე მერჯავს და მერე იქ აგრძელებს დაკომიტებას...  გაარკვიეთ რომელ ბრენჩზე ხართ და ყველამ იმუშაოს develop-ზე.

**Comment by nikoloz14** [comment]
შემთხვევით დაგვემერჯა, დავარევერთეთ... გვაპატიეთ არ ვართ მიჩვეული ამ ბრენჩებს :D
